### ISSUE TITLE
Request: Yosemite color scheme

### ISSUE THREAD

**Issue by fa7ad** [horst3180/Ceti-3.14-theme#5]
Hi,
Could you possibly port this theme to fit yosemite color scheme?

This theme is perfect as is, but I love the UI of Yosemite and so far the themes I've found for GNOME 3.14 are either incomplete, look like SL/Lion at best, buggy.

Regards

**Comment by horst3180** [comment]
Sorry, this theme is not meant to be a Yosemite look-alike. Also I currently don't have the time to do this.

**Comment by fa7ad** [comment]
Okay, I understand.

Could you maybe look at [this repo](https://github.com/fa7ad/xgtk-kxmylo)?

The theme is by _kxmylo_ on DA, I created the repo because he is no longer responding to issues on DA.
I fixed some of the initial problems, but my knowledge of theming is really limited.

So, it would be really nice if you could see and help fix a few issues :smile:

**Comment by horst3180** [comment]
I'll see if I can do something. Maybe point out the problems in the issues section of that repo and I'll have a look.

**Comment by fa7ad** [comment]
Thanks a lot man
*Respect*

**Comment by fa7ad** [comment]
@horst3180 Hey, I added some of the issues in my repo. please have a look whenever you get time :smiley:
