### ISSUE TITLE
Theme partly implemented

### ISSUE THREAD

**Issue by talesam** [horst3180/Ceti-3.14-theme#6]
I made a video to show that the subject was given partially. I wonder what the icons that you used, I would use them.
The theme was not applied in the dock and not the settings, where I click to turn off or log out.

https://www.youtube.com/watch?v=RdOW9LbAVo8&feature=youtu.be

**Comment by horst3180** [comment]
You have to select the shell theme in gnome tweak tool, too or just do

    gsettings set org.gnome.shell.extensions.user-theme name "Ceti-3.14"

Note, that you need the "User Theme" extension for Gnome Shell, if you don't have it already.

The Icons I used in the screenshot are not released yet. I have to do some work on them before I make them publicly available.

**Comment by talesam** [comment]
my extension "User Theme" is giving error when activating, take a look! Do you know how to solve?

http://i.imgur.com/MIoKUts.png

**Comment by horst3180** [comment]
I'm not sure what's going wrong there. Where did you install the theme? Do other themes work?

**Comment by talesam** [comment]
You can not install the extension "User Theme" is giving error.

See:
http://i.imgur.com/N3zcOZc.png
http://i.imgur.com/T40THde.png

**Comment by horst3180** [comment]
Ah ok, that's the problem I guess. Maybe your distribution has a package available to install from the package manager. This should work. In Archlinux for example there's a package called gnome-shell-extensions which contains some extensions including user theme, but I don't know wether it's available elsewhere.

**Comment by talesam** [comment]
I do not know what I did, but is now working: p

**Comment by horst3180** [comment]
Ok, this can be closed. Good to know you solved it.
